package:
  name: menpofit
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - menpo 0.4.0|>=0.4.1,<0.5.0  # Make sure we ignore the alpha
    - scikit-learn 0.15.*

test:
  requires:
  - coverage
  - nose
  - mock

  imports:
  - menpofit

  commands:
  - python -c "import nose; nose.main()" -s menpofit

about:
  home: https://github.com/menpo/menpofit/
  license: BSD
